[features]
seeds = false
[programs.localnet]
merkleclaimcontract = "A9ftjBP1g4zBRozNKPT4Pt913Jyc3BYWtS5pBfxj7FwH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mi/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[test]
startup_wait = 1000000